"""convert property_type to enum

Revision ID: 9a54f82ad34a
Revises: 2c3fcf4a7c87
Create Date: 2026-09-18 05:20:20.565680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a54f82ad34a'
down_revision: Union[str, Sequence[str], None] = '2c3fcf4a7c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Normalize existing data to match enum values before type change
    op.execute("""
        UPDATE properties
        SET property_type = 'Independent House'
        WHERE lower(trim(property_type)) = 'independent house'
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first (IF NOT EXISTS handles re-runs), then alter column with explicit cast
    op.execute("CREATE TYPE propertytypeenum AS ENUM ('apartment', 'villa', 'plot', 'Independent House')")
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('apartment', 'villa', 'plot', 'Independent House', name='propertytypeenum'),
               postgresql_using="property_type::propertytypeenum",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'property_type',
               existing_type=sa.Enum('apartment', 'villa', 'plot', 'Independent House', name='propertytypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.execute("DROP TYPE IF EXISTS propertytypeenum")
    # ### end Alembic commands ###